PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

INSERT DATA{

graph <http://mu.semte.ch/graphs/public> {

<http://bittich.be/whatever> a <http://bittich.be/Youpi>;
                        mu:uuid "ab5506d9-e2c5-40f3-992d-540bb86a6b65";
                        <http://bittich.be/woops> "published";
                        <http://bittich.be/vector> "[0.5, 10, 6]".

}
}

;
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

INSERT DATA{

graph <http://mu.semte.ch/graphs/public> {

<http://bittich.be/whatever2> a <http://bittich.be/Youpi>;
                        mu:uuid "ab5506d9-e2c5-40f3-992d-540bb86a6b66";
                        <http://bittich.be/woops> "published";
                        <http://bittich.be/vector> "[-0.5, 10, 10]".

}
}