INSERT DATA {
  GRAPH <http://mu.semte.ch/application> {
    <share://semantic-forms/20200827091312-forms.ttl>	<http://purl.org/dc/terms/modified>	"2020-08-27T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    <share://semantic-forms/20210222214348-forms.ttl>	<http://purl.org/dc/terms/type>	<http://data.lblod.gift/concepts/form-file-type> .
    <share://semantic-forms/20201028125351-forms.ttl>	<http://purl.org/dc/terms/format>	"text/turtle" .
    <share://semantic-forms/20210208122305-forms.ttl>	<http://purl.org/dc/terms/format>	"text/turtle" .
    <share://semantic-forms/20200827091312-forms.ttl>	<http://purl.org/dc/terms/created>	"2020-08-27T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    <share://semantic-forms/20201028125351-forms.ttl>	<http://mu.semte.ch/vocabularies/core/uuid>	"899df36a-76d7-438b-a595-898f216fa979" .
    <share://semantic-forms/20200827091312-forms.ttl>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName>	"20200827091312-forms.ttl" .
    <share://semantic-forms/20200508151443-forms.ttl>	<http://mu.semte.ch/vocabularies/core/uuid>	"cdd621e6-1284-47b1-a24d-95f7521120bf" .
    <share://semantic-forms/20210222214348-forms.ttl>	<http://dbpedia.org/resource/fileExtension>	"ttl" .
    <share://semantic-forms/20210222214348-forms.ttl>	<http://purl.org/dc/terms/format>	"text/turtle" .
    <share://semantic-forms/20200508151443-forms.ttl>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName>	"20200508151443-forms.ttl" .
    <share://semantic-forms/20210120121332-forms.ttl>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName>	"20210120121332-forms.ttl" .
    <share://semantic-forms/20210706102126-forms.ttl>	<http://dbpedia.org/resource/fileExtension>	"ttl" .
    <share://semantic-forms/20210222214348-forms.ttl>	<http://mu.semte.ch/vocabularies/core/uuid>	"e9761fdd-5476-426d-b099-8b55e7c15c1e" .
    <share://semantic-forms/20200827091312-forms.ttl>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileSize>	"123000"^^<http://www.w3.org/2001/XMLSchema#integer> .
    <share://semantic-forms/20210628105019-forms.ttl>	<http://purl.org/dc/terms/type>	<http://data.lblod.gift/concepts/form-file-type> .
    <share://semantic-forms/20200827091312-forms.ttl>	<http://mu.semte.ch/vocabularies/core/uuid>	"03f4780c-438c-4be9-a9b8-cab560fc8122" .
    <share://semantic-forms/20200508151443-forms.ttl>	<http://dbpedia.org/resource/fileExtension>	"ttl" .
    <share://semantic-forms/20210628105019-forms.ttl>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileSize>	"272084"^^<http://www.w3.org/2001/XMLSchema#integer> .
    <share://semantic-forms/20210208122305-forms.ttl>	<http://dbpedia.org/resource/fileExtension>	"ttl" .
    <share://semantic-forms/20210120121332-forms.ttl>	<http://purl.org/dc/terms/type>	<http://data.lblod.gift/concepts/form-file-type> .
    <share://semantic-forms/20210120121332-forms.ttl>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject> .
    <share://semantic-forms/20201028125351-forms.ttl>	<http://purl.org/dc/terms/type>	<http://data.lblod.gift/concepts/form-file-type> .
    <share://semantic-forms/20201028125351-forms.ttl>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName>	"20201028125351-forms.ttl" .
    <share://semantic-forms/20201028125351-forms.ttl>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileSize>	"248000"^^<http://www.w3.org/2001/XMLSchema#integer> .
    <share://semantic-forms/20210120121332-forms.ttl>	<http://purl.org/dc/terms/modified>	"2021-01-20T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    <share://semantic-forms/20210628105019-forms.ttl>	<http://dbpedia.org/resource/fileExtension>	"ttl" .
    <share://semantic-forms/20210706102126-forms.ttl>	<http://mu.semte.ch/vocabularies/core/uuid>	"9a9b14ab-e1bf-4185-adbb-df86aa7bdaaf" .
    <share://semantic-forms/20210120121332-forms.ttl>	<http://purl.org/dc/terms/created>	"2021-01-20T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    <share://semantic-forms/20210706102126-forms.ttl>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName>	"20210706102126-forms.ttl" .
    <share://semantic-forms/20200827091312-forms.ttl>	<http://purl.org/dc/terms/type>	<http://data.lblod.gift/concepts/form-file-type> .
    <share://semantic-forms/20210222214348-forms.ttl>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName>	"20210222214348-forms.ttl" .
    <share://semantic-forms/20200508151443-forms.ttl>	<http://purl.org/dc/terms/created>	"2020-05-08T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    <share://semantic-forms/20210120121332-forms.ttl>	<http://mu.semte.ch/vocabularies/core/uuid>	"dfb3c5b7-31e8-4764-9d3b-d34b83c9724d" .
    <share://semantic-forms/20210628105019-forms.ttl>	<http://mu.semte.ch/vocabularies/core/uuid>	"d5ea6d81-55f9-4373-955f-b727e1c00260" .
    <share://semantic-forms/20210208122305-forms.ttl>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName>	"20210208122305-forms.ttl" .
    <share://semantic-forms/20200508151443-forms.ttl>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject> .
    <share://semantic-forms/20200508151443-forms.ttl>	<http://purl.org/dc/terms/modified>	"2020-05-08T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    <share://semantic-forms/20210120121332-forms.ttl>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileSize>	"250300"^^<http://www.w3.org/2001/XMLSchema#integer> .
    <share://semantic-forms/20210628105019-forms.ttl>	<http://purl.org/dc/terms/created>	"2021-06-28T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    <share://semantic-forms/20210706102126-forms.ttl>	<http://purl.org/dc/terms/format>	"text/turtle" .
    <share://semantic-forms/20210706102126-forms.ttl>	<http://purl.org/dc/terms/created>	"2021-07-06T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    <share://semantic-forms/20210628105019-forms.ttl>	<http://purl.org/dc/terms/modified>	"2021-06-28T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    <share://semantic-forms/20210706102126-forms.ttl>	<http://purl.org/dc/terms/modified>	"2021-07-06T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    <share://semantic-forms/20210222214348-forms.ttl>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject> .
    <share://semantic-forms/20200827091312-forms.ttl>	<http://dbpedia.org/resource/fileExtension>	"ttl" .
    <share://semantic-forms/20200827091312-forms.ttl>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject> .
    <share://semantic-forms/20200827091312-forms.ttl>	<http://purl.org/dc/terms/format>	"text/turtle" .
    <share://semantic-forms/20210628105019-forms.ttl>	<http://purl.org/dc/terms/format>	"text/turtle" .
    <share://semantic-forms/20210706102126-forms.ttl>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileSize>	"271300"^^<http://www.w3.org/2001/XMLSchema#integer> .
    <share://semantic-forms/20210222214348-forms.ttl>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileSize>	"265045"^^<http://www.w3.org/2001/XMLSchema#integer> .
    <share://semantic-forms/20210706102126-forms.ttl>	<http://purl.org/dc/terms/type>	<http://data.lblod.gift/concepts/form-file-type> .
    <share://semantic-forms/20210120121332-forms.ttl>	<http://purl.org/dc/terms/format>	"text/turtle" .
    <share://semantic-forms/20210208122305-forms.ttl>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject> .
    <share://semantic-forms/20200508151443-forms.ttl>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileSize>	"123000"^^<http://www.w3.org/2001/XMLSchema#integer> .
    <share://semantic-forms/20201028125351-forms.ttl>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject> .
    <share://semantic-forms/20200508151443-forms.ttl>	<http://purl.org/dc/terms/type>	<http://data.lblod.gift/concepts/form-file-type> .
    <share://semantic-forms/20200508151443-forms.ttl>	<http://purl.org/dc/terms/format>	"text/turtle" .
    <share://semantic-forms/20210628105019-forms.ttl>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName>	"20210628105019-forms.ttl" .
    <share://semantic-forms/20210628105019-forms.ttl>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject> .
    <share://semantic-forms/20201028125351-forms.ttl>	<http://dbpedia.org/resource/fileExtension>	"ttl" .
    <share://semantic-forms/20201028125351-forms.ttl>	<http://purl.org/dc/terms/created>	"2020-10-28T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    <share://semantic-forms/20210222214348-forms.ttl>	<http://purl.org/dc/terms/modified>	"2021-02-22T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    <share://semantic-forms/20210706102126-forms.ttl>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject> .
    <share://semantic-forms/20210208122305-forms.ttl>	<http://purl.org/dc/terms/created>	"2021-02-08T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    <share://semantic-forms/20210208122305-forms.ttl>	<http://mu.semte.ch/vocabularies/core/uuid>	"cca21232-4662-46f4-9cab-b1169d5599f8" .
    <share://semantic-forms/20210208122305-forms.ttl>	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileSize>	"262727"^^<http://www.w3.org/2001/XMLSchema#integer> .
    <share://semantic-forms/20201028125351-forms.ttl>	<http://purl.org/dc/terms/modified>	"2020-10-28T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    <share://semantic-forms/20210222214348-forms.ttl>	<http://purl.org/dc/terms/created>	"2021-02-22T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    <share://semantic-forms/20210120121332-forms.ttl>	<http://dbpedia.org/resource/fileExtension>	"ttl" .
    <share://semantic-forms/20210208122305-forms.ttl>	<http://purl.org/dc/terms/modified>	"2021-02-08T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    <share://semantic-forms/20210208122305-forms.ttl>	<http://purl.org/dc/terms/type>	<http://data.lblod.gift/concepts/form-file-type> .
  }
}
